### ISSUE TITLE
Hitting enter in text field should submit form

### ISSUE THREAD

**Issue by mattco98** [ChatTriggers/website-frontend#23]
If you're in, say, the login page, you have both fields filled in, and you hit the enter key, the form should be submitted. As of now, you have to click the login button to submit the form. This should happen everywhere, where applicable.

**Comment by Satnik** [comment]
I want to you help you with your issue but when i start localhost i see only blanked website where is problem ?

**Comment by mattco98** [comment]
Yeah, everything's on `localhost:3000/modules`, I haven't done anything with the home page yet. I should probably just add some text stating that.

**Comment by Satnik** [comment]
Ok, i will take it :)

**Comment by Satnik** [comment]
i fixed this issue and also this #30 but i don't have Permission to push new branch ... pls add me :)

**Comment by mattco98** [comment]
That's not quite how GitHub works. You have to fork this repo, push your changes to your fork, and then open a pull request. You can find more information online if you need it.

**Comment by mattco98** [comment]
Fixed in #37
