### ISSUE TITLE
No way to manually download a module

### ISSUE THREAD

**Issue by kerbybit** [ChatTriggers/website-frontend#48]
There is no way to manually download a module to take a peak at the code without importing it with the command

**Comment by kerbybit** [comment]
This is extra important because anything before 1.0.0 will not be able to import with the command due to API changes

**Comment by mattco98** [comment]
Releases have a download scripts button. And importing will work for 0.18.4; if the mod doesn’t send the version with the import request (or whatever, false did that part), it’ll assume 0.18.4.
