### ISSUE TITLE
Release description editor only renders a small piece of the last line of text

### ISSUE THREAD

**Issue by jhmaster2000** [ChatTriggers/website-frontend#51]
The image speaks for itself
![image](https://user-images.githubusercontent.com/32803471/68507542-ea4d6e80-024a-11ea-8ad0-33dd4d98f8fa.png)

**Comment by jhmaster2000** [comment]
Further testing shows it doesnt matter the line amount this always happens to the last line
![image](https://user-images.githubusercontent.com/32803471/68507763-6f388800-024b-11ea-92df-fd68b805a52c.png)

**Comment by mattco98** [comment]
No, it really doesn't speak for itself. I can't possibly reproduce this issue with zero details. On what device are you viewing the website? What OS? What browser version?

**Comment by jhmaster2000** [comment]
> No, it really doesn't speak for itself. I can't possibly reproduce this issue with zero details. On what device are you viewing the website? What OS? What browser version?

Oh yeah right, my bad, wasnt really thinking straight when making this lol

OS: Windows 10 Pro Version 1903 (Build 18362.418)
Browser: Stable Chrome 78.0.3904.87 (Official Build) (64-bit)
Javascript: V8 7.8.279.19

Steps to reproduce: Go to a module you own with a release that was autogenerated from the old website and press the release's edit button.

**Comment by mattco98** [comment]
Closing in favor of #52.
