### ISSUE TITLE
Releases description doesn't newline unless there is an empty line inbetween.

### ISSUE THREAD

**Issue by jhmaster2000** [ChatTriggers/website-frontend#53]
The video only showcases the issue happening on preview but it does actually happen when saving the description aswell (Not a preview-only bug)
https://file.coffee/f1NAiH_U2e.mp4

### System Info
OS: Windows 10 Pro Version 1903 (Build 18362.418)
Browser: Stable Chrome 78.0.3904.87 (Official Build) (64-bit)
Javascript: V8 7.8.279.19

**Comment by mattco98** [comment]
That's the way markdown works.
