### ISSUE TITLE
Module preview should be limited in height

### ISSUE THREAD

**Issue by kerbybit** [ChatTriggers/website-frontend#60]
Right now, module preview from the main module list has no height restriction:
![unknown](https://user-images.githubusercontent.com/10331479/70327513-92c80180-17fc-11ea-8196-11aea8b8bc11.png)
Although it is nice to have a longer description, there is a point where it should cut off or start scrolling

for cases like the one shown above, it *might* be worth it to have a separate, optional input box as sort of a "readme" that doesn't show up in the module preview at all but will show up once the user clicks "view"

**Comment by mattco98** [comment]
Fixed in fc8d32e
